import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Image from 'next/image';
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.Home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
          <div className={styles.textContent}>
              <h1 className={styles.smallText}>I&apos;m</h1>
              <h1 className={styles.glow}>Abdullah Islam</h1>
              <p className={styles.description}>Full Stack Web Developer from Pakistan,Lahore specializing in creating web applications using MERN stack.</p>
          </div>
          <div className={styles.framed} >
          <Image src="/profile.jpg" layout='fill' alt="profile-photo" objectFit='cover'/>
          </div>
      </div>
      <div className={styles.button} onClick={()=>router.push("/projects")}>
  <div className={styles.button__text}>Discover more...</div>
  
  <div className={styles.button__wrapper}>
    <div className={styles.button__arrow}></div>
    <div className={styles.button__borderCircle}></div>
    <div className={styles.button__maskCircle}>
      <div className={styles.button__smallCircle}></div>
    </div>
  </div>
</div>
   </div>
  )
}
